// ignore_for_file: unused_element, unused_field

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint
import 'dart:ffi' as ffi;

/// Bindings for the ScreenGot native library.
class ScreenGot {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  ScreenGot(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  ScreenGot.fromLookup(
    ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName) lookup,
  ) : _lookup = lookup;

  int _GoStringLen(_GoString_ s) {
    return __GoStringLen(s);
  }

  late final __GoStringLenPtr =
      _lookup<ffi.NativeFunction<ffi.Size Function(_GoString_)>>(
        '_GoStringLen',
      );
  late final __GoStringLen = __GoStringLenPtr
      .asFunction<int Function(_GoString_)>();

  ffi.Pointer<ffi.Char> _GoStringPtr(_GoString_ s) {
    return __GoStringPtr(s);
  }

  late final __GoStringPtrPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Char> Function(_GoString_)>>(
        '_GoStringPtr',
      );
  late final __GoStringPtr = __GoStringPtrPtr
      .asFunction<ffi.Pointer<ffi.Char> Function(_GoString_)>();

  void RegisterPort(int port) {
    return _RegisterPort(port);
  }

  late final _RegisterPortPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.LongLong)>>(
        'RegisterPort',
      );
  late final _RegisterPort = _RegisterPortPtr.asFunction<void Function(int)>();

  void UnregisterPort() {
    return _UnregisterPort();
  }

  late final _UnregisterPortPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function()>>('UnregisterPort');
  late final _UnregisterPort = _UnregisterPortPtr.asFunction<void Function()>();

  void StopTask(int taskID, int port) {
    return _StopTask(taskID, port);
  }

  late final _StopTaskPtr =
      _lookup<
        ffi.NativeFunction<ffi.Void Function(ffi.LongLong, ffi.LongLong)>
      >('StopTask');
  late final _StopTask = _StopTaskPtr.asFunction<void Function(int, int)>();

  void BridgeInit(ffi.Pointer<ffi.Void> api) {
    return _BridgeInit(api);
  }

  late final _BridgeInitPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'BridgeInit',
      );
  late final _BridgeInit =
      _BridgeInitPtr.asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void Move(int x, int y, int port) {
    return _Move(x, y, port);
  }

  late final _MovePtr =
      _lookup<
        ffi.NativeFunction<ffi.Void Function(ffi.Int, ffi.Int, ffi.LongLong)>
      >('Move');
  late final _Move = _MovePtr.asFunction<void Function(int, int, int)>();

  void MoveRelative(int x, int y, int port) {
    return _MoveRelative(x, y, port);
  }

  late final _MoveRelativePtr =
      _lookup<
        ffi.NativeFunction<ffi.Void Function(ffi.Int, ffi.Int, ffi.LongLong)>
      >('MoveRelative');
  late final _MoveRelative =
      _MoveRelativePtr.asFunction<void Function(int, int, int)>();

  void Click(ffi.Pointer<ffi.Char> btn, int dbl, int port) {
    return _Click(btn, dbl, port);
  }

  late final _ClickPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<ffi.Char>, ffi.Int, ffi.LongLong)
        >
      >('Click');
  late final _Click =
      _ClickPtr.asFunction<void Function(ffi.Pointer<ffi.Char>, int, int)>();

  void Toggle(ffi.Pointer<ffi.Char> btn, ffi.Pointer<ffi.Char> dir, int port) {
    return _Toggle(btn, dir, port);
  }

  late final _TogglePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Char>,
            ffi.LongLong,
          )
        >
      >('Toggle');
  late final _Toggle =
      _TogglePtr.asFunction<
        void Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>, int)
      >();

  void Scroll(int x, int y, int port) {
    return _Scroll(x, y, port);
  }

  late final _ScrollPtr =
      _lookup<
        ffi.NativeFunction<ffi.Void Function(ffi.Int, ffi.Int, ffi.LongLong)>
      >('Scroll');
  late final _Scroll = _ScrollPtr.asFunction<void Function(int, int, int)>();

  void ScrollDir(int amount, ffi.Pointer<ffi.Char> dir, int port) {
    return _ScrollDir(amount, dir, port);
  }

  late final _ScrollDirPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(ffi.Int, ffi.Pointer<ffi.Char>, ffi.LongLong)
        >
      >('ScrollDir');
  late final _ScrollDir =
      _ScrollDirPtr.asFunction<
        void Function(int, ffi.Pointer<ffi.Char>, int)
      >();

  void GetLocation(int port) {
    return _GetLocation(port);
  }

  late final _GetLocationPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.LongLong)>>(
        'GetLocation',
      );
  late final _GetLocation = _GetLocationPtr.asFunction<void Function(int)>();

  void SetMouseSleep(int ms, int port) {
    return _SetMouseSleep(ms, port);
  }

  late final _SetMouseSleepPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int, ffi.LongLong)>>(
        'SetMouseSleep',
      );
  late final _SetMouseSleep =
      _SetMouseSleepPtr.asFunction<void Function(int, int)>();

  void MilliSleep(int ms, int port) {
    return _MilliSleep(ms, port);
  }

  late final _MilliSleepPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int, ffi.LongLong)>>(
        'MilliSleep',
      );
  late final _MilliSleep = _MilliSleepPtr.asFunction<void Function(int, int)>();

  int MoveSmoothStart(int x, int y, int port) {
    return _MoveSmoothStart(x, y, port);
  }

  late final _MoveSmoothStartPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.LongLong Function(ffi.Int, ffi.Int, ffi.LongLong)
        >
      >('MoveSmoothStart');
  late final _MoveSmoothStart =
      _MoveSmoothStartPtr.asFunction<int Function(int, int, int)>();

  int DragSmoothStart(int x, int y, int port) {
    return _DragSmoothStart(x, y, port);
  }

  late final _DragSmoothStartPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.LongLong Function(ffi.Int, ffi.Int, ffi.LongLong)
        >
      >('DragSmoothStart');
  late final _DragSmoothStart =
      _DragSmoothStartPtr.asFunction<int Function(int, int, int)>();

  int ScrollSmoothStart(int x, int y, int port) {
    return _ScrollSmoothStart(x, y, port);
  }

  late final _ScrollSmoothStartPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.LongLong Function(ffi.Int, ffi.Int, ffi.LongLong)
        >
      >('ScrollSmoothStart');
  late final _ScrollSmoothStart =
      _ScrollSmoothStartPtr.asFunction<int Function(int, int, int)>();

  void TypeStr(ffi.Pointer<ffi.Char> text, int port) {
    return _TypeStr(text, port);
  }

  late final _TypeStrPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<ffi.Char>, ffi.LongLong)
        >
      >('TypeStr');
  late final _TypeStr =
      _TypeStrPtr.asFunction<void Function(ffi.Pointer<ffi.Char>, int)>();

  void TypeStrWithInts(
    ffi.Pointer<ffi.Char> text,
    int arg1,
    int arg2,
    int port,
  ) {
    return _TypeStrWithInts(text, arg1, arg2, port);
  }

  late final _TypeStrWithIntsPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Pointer<ffi.Char>,
            ffi.Int,
            ffi.Int,
            ffi.LongLong,
          )
        >
      >('TypeStrWithInts');
  late final _TypeStrWithInts =
      _TypeStrWithIntsPtr.asFunction<
        void Function(ffi.Pointer<ffi.Char>, int, int, int)
      >();

  void Sleep(int seconds, int port) {
    return _Sleep(seconds, port);
  }

  late final _SleepPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int, ffi.LongLong)>>(
        'Sleep',
      );
  late final _Sleep = _SleepPtr.asFunction<void Function(int, int)>();

  void SetKeySleep(int ms, int port) {
    return _SetKeySleep(ms, port);
  }

  late final _SetKeySleepPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int, ffi.LongLong)>>(
        'SetKeySleep',
      );
  late final _SetKeySleep =
      _SetKeySleepPtr.asFunction<void Function(int, int)>();

  void KeyTap(ffi.Pointer<ffi.Char> key, ffi.Pointer<ffi.Char> mods, int port) {
    return _KeyTap(key, mods, port);
  }

  late final _KeyTapPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Char>,
            ffi.LongLong,
          )
        >
      >('KeyTap');
  late final _KeyTap =
      _KeyTapPtr.asFunction<
        void Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>, int)
      >();

  void KeyTapArr(
    ffi.Pointer<ffi.Char> key,
    ffi.Pointer<ffi.Char> modsJson,
    int port,
  ) {
    return _KeyTapArr(key, modsJson, port);
  }

  late final _KeyTapArrPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Char>,
            ffi.LongLong,
          )
        >
      >('KeyTapArr');
  late final _KeyTapArr =
      _KeyTapArrPtr.asFunction<
        void Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>, int)
      >();

  void KeyToggle(
    ffi.Pointer<ffi.Char> key,
    ffi.Pointer<ffi.Char> direction,
    int port,
  ) {
    return _KeyToggle(key, direction, port);
  }

  late final _KeyTogglePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Char>,
            ffi.LongLong,
          )
        >
      >('KeyToggle');
  late final _KeyToggle =
      _KeyTogglePtr.asFunction<
        void Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>, int)
      >();

  void WriteAll(ffi.Pointer<ffi.Char> text, int port) {
    return _WriteAll(text, port);
  }

  late final _WriteAllPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<ffi.Char>, ffi.LongLong)
        >
      >('WriteAll');
  late final _WriteAll =
      _WriteAllPtr.asFunction<void Function(ffi.Pointer<ffi.Char>, int)>();

  void ReadAll(int port) {
    return _ReadAll(port);
  }

  late final _ReadAllPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.LongLong)>>('ReadAll');
  late final _ReadAll = _ReadAllPtr.asFunction<void Function(int)>();

  int TypeStrStart(ffi.Pointer<ffi.Char> text, int port) {
    return _TypeStrStart(text, port);
  }

  late final _TypeStrStartPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.LongLong Function(ffi.Pointer<ffi.Char>, ffi.LongLong)
        >
      >('TypeStrStart');
  late final _TypeStrStart =
      _TypeStrStartPtr.asFunction<int Function(ffi.Pointer<ffi.Char>, int)>();

  void GetPixelColor(int x, int y, int port) {
    return _GetPixelColor(x, y, port);
  }

  late final _GetPixelColorPtr =
      _lookup<
        ffi.NativeFunction<ffi.Void Function(ffi.Int, ffi.Int, ffi.LongLong)>
      >('GetPixelColor');
  late final _GetPixelColor =
      _GetPixelColorPtr.asFunction<void Function(int, int, int)>();

  void GetScreenSize(int port) {
    return _GetScreenSize(port);
  }

  late final _GetScreenSizePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.LongLong)>>(
        'GetScreenSize',
      );
  late final _GetScreenSize =
      _GetScreenSizePtr.asFunction<void Function(int)>();

  void CaptureScreenSave(
    int x,
    int y,
    int w,
    int h,
    ffi.Pointer<ffi.Char> path,
    int port,
  ) {
    return _CaptureScreenSave(x, y, w, h, path, port);
  }

  late final _CaptureScreenSavePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int,
            ffi.Int,
            ffi.Int,
            ffi.Int,
            ffi.Pointer<ffi.Char>,
            ffi.LongLong,
          )
        >
      >('CaptureScreenSave');
  late final _CaptureScreenSave =
      _CaptureScreenSavePtr.asFunction<
        void Function(int, int, int, int, ffi.Pointer<ffi.Char>, int)
      >();

  void CaptureScreenBase64(int x, int y, int w, int h, int port) {
    return _CaptureScreenBase64(x, y, w, h, port);
  }

  late final _CaptureScreenBase64Ptr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(ffi.Int, ffi.Int, ffi.Int, ffi.Int, ffi.LongLong)
        >
      >('CaptureScreenBase64');
  late final _CaptureScreenBase64 =
      _CaptureScreenBase64Ptr.asFunction<
        void Function(int, int, int, int, int)
      >();

  void DisplaysNum(int port) {
    return _DisplaysNum(port);
  }

  late final _DisplaysNumPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.LongLong)>>(
        'DisplaysNum',
      );
  late final _DisplaysNum = _DisplaysNumPtr.asFunction<void Function(int)>();

  void GetDisplayBounds(int index, int port) {
    return _GetDisplayBounds(index, port);
  }

  late final _GetDisplayBoundsPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int, ffi.LongLong)>>(
        'GetDisplayBounds',
      );
  late final _GetDisplayBounds =
      _GetDisplayBoundsPtr.asFunction<void Function(int, int)>();

  void CaptureDisplaySave(int index, ffi.Pointer<ffi.Char> path, int port) {
    return _CaptureDisplaySave(index, path, port);
  }

  late final _CaptureDisplaySavePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(ffi.Int, ffi.Pointer<ffi.Char>, ffi.LongLong)
        >
      >('CaptureDisplaySave');
  late final _CaptureDisplaySave =
      _CaptureDisplaySavePtr.asFunction<
        void Function(int, ffi.Pointer<ffi.Char>, int)
      >();

  void CaptureDisplayRegionSave(
    int index,
    int x,
    int y,
    int w,
    int h,
    ffi.Pointer<ffi.Char> path,
    int port,
  ) {
    return _CaptureDisplayRegionSave(index, x, y, w, h, path, port);
  }

  late final _CaptureDisplayRegionSavePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int,
            ffi.Int,
            ffi.Int,
            ffi.Int,
            ffi.Int,
            ffi.Pointer<ffi.Char>,
            ffi.LongLong,
          )
        >
      >('CaptureDisplayRegionSave');
  late final _CaptureDisplayRegionSave =
      _CaptureDisplayRegionSavePtr.asFunction<
        void Function(int, int, int, int, int, ffi.Pointer<ffi.Char>, int)
      >();

  void SaveImageJpeg(ffi.Pointer<ffi.Char> path, int quality, int port) {
    return _SaveImageJpeg(path, quality, port);
  }

  late final _SaveImageJpegPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<ffi.Char>, ffi.Int, ffi.LongLong)
        >
      >('SaveImageJpeg');
  late final _SaveImageJpeg =
      _SaveImageJpegPtr.asFunction<
        void Function(ffi.Pointer<ffi.Char>, int, int)
      >();

  void SaveImagePNGFromCaptureImg(ffi.Pointer<ffi.Char> path, int port) {
    return _SaveImagePNGFromCaptureImg(path, port);
  }

  late final _SaveImagePNGFromCaptureImgPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<ffi.Char>, ffi.LongLong)
        >
      >('SaveImagePNGFromCaptureImg');
  late final _SaveImagePNGFromCaptureImg =
      _SaveImagePNGFromCaptureImgPtr.asFunction<
        void Function(ffi.Pointer<ffi.Char>, int)
      >();

  void CaptureScreenBitmapSave(
    int x,
    int y,
    int w,
    int h,
    ffi.Pointer<ffi.Char> path,
    int port,
  ) {
    return _CaptureScreenBitmapSave(x, y, w, h, path, port);
  }

  late final _CaptureScreenBitmapSavePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int,
            ffi.Int,
            ffi.Int,
            ffi.Int,
            ffi.Pointer<ffi.Char>,
            ffi.LongLong,
          )
        >
      >('CaptureScreenBitmapSave');
  late final _CaptureScreenBitmapSave =
      _CaptureScreenBitmapSavePtr.asFunction<
        void Function(int, int, int, int, ffi.Pointer<ffi.Char>, int)
      >();

  void FindBitmapFromCapture(int x, int y, int w, int h, int port) {
    return _FindBitmapFromCapture(x, y, w, h, port);
  }

  late final _FindBitmapFromCapturePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(ffi.Int, ffi.Int, ffi.Int, ffi.Int, ffi.LongLong)
        >
      >('FindBitmapFromCapture');
  late final _FindBitmapFromCapture =
      _FindBitmapFromCapturePtr.asFunction<
        void Function(int, int, int, int, int)
      >();

  void FindAllBitmapFromCapture(int x, int y, int w, int h, int port) {
    return _FindAllBitmapFromCapture(x, y, w, h, port);
  }

  late final _FindAllBitmapFromCapturePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(ffi.Int, ffi.Int, ffi.Int, ffi.Int, ffi.LongLong)
        >
      >('FindAllBitmapFromCapture');
  late final _FindAllBitmapFromCapture =
      _FindAllBitmapFromCapturePtr.asFunction<
        void Function(int, int, int, int, int)
      >();

  void MoveToFoundBitmap(int x, int y, int w, int h, int port) {
    return _MoveToFoundBitmap(x, y, w, h, port);
  }

  late final _MoveToFoundBitmapPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(ffi.Int, ffi.Int, ffi.Int, ffi.Int, ffi.LongLong)
        >
      >('MoveToFoundBitmap');
  late final _MoveToFoundBitmap =
      _MoveToFoundBitmapPtr.asFunction<
        void Function(int, int, int, int, int)
      >();

  void SaveBitmapToFile(
    int x,
    int y,
    int w,
    int h,
    ffi.Pointer<ffi.Char> path,
    int port,
  ) {
    return _SaveBitmapToFile(x, y, w, h, path, port);
  }

  late final _SaveBitmapToFilePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int,
            ffi.Int,
            ffi.Int,
            ffi.Int,
            ffi.Pointer<ffi.Char>,
            ffi.LongLong,
          )
        >
      >('SaveBitmapToFile');
  late final _SaveBitmapToFile =
      _SaveBitmapToFilePtr.asFunction<
        void Function(int, int, int, int, ffi.Pointer<ffi.Char>, int)
      >();

  void SaveCaptureRegion(
    ffi.Pointer<ffi.Char> path,
    int x,
    int y,
    int w,
    int h,
    int port,
  ) {
    return _SaveCaptureRegion(path, x, y, w, h, port);
  }

  late final _SaveCaptureRegionPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Pointer<ffi.Char>,
            ffi.Int,
            ffi.Int,
            ffi.Int,
            ffi.Int,
            ffi.LongLong,
          )
        >
      >('SaveCaptureRegion');
  late final _SaveCaptureRegion =
      _SaveCaptureRegionPtr.asFunction<
        void Function(ffi.Pointer<ffi.Char>, int, int, int, int, int)
      >();

  void SaveCaptureFull(ffi.Pointer<ffi.Char> path, int port) {
    return _SaveCaptureFull(path, port);
  }

  late final _SaveCaptureFullPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<ffi.Char>, ffi.LongLong)
        >
      >('SaveCaptureFull');
  late final _SaveCaptureFull =
      _SaveCaptureFullPtr.asFunction<
        void Function(ffi.Pointer<ffi.Char>, int)
      >();

  void GcvFindAllImgFile(
    ffi.Pointer<ffi.Char> templatePath,
    ffi.Pointer<ffi.Char> targetPath,
    int port,
  ) {
    return _GcvFindAllImgFile(templatePath, targetPath, port);
  }

  late final _GcvFindAllImgFilePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Char>,
            ffi.LongLong,
          )
        >
      >('GcvFindAllImgFile');
  late final _GcvFindAllImgFile =
      _GcvFindAllImgFilePtr.asFunction<
        void Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>, int)
      >();

  void GcvFindAllImgFilesDecoded(
    ffi.Pointer<ffi.Char> templatePath,
    ffi.Pointer<ffi.Char> targetPath,
    int port,
  ) {
    return _GcvFindAllImgFilesDecoded(templatePath, targetPath, port);
  }

  late final _GcvFindAllImgFilesDecodedPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Char>,
            ffi.LongLong,
          )
        >
      >('GcvFindAllImgFilesDecoded');
  late final _GcvFindAllImgFilesDecoded =
      _GcvFindAllImgFilesDecodedPtr.asFunction<
        void Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>, int)
      >();

  void GcvFindXFromFile(
    ffi.Pointer<ffi.Char> templatePath,
    ffi.Pointer<ffi.Char> targetPath,
    int port,
  ) {
    return _GcvFindXFromFile(templatePath, targetPath, port);
  }

  late final _GcvFindXFromFilePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Char>,
            ffi.LongLong,
          )
        >
      >('GcvFindXFromFile');
  late final _GcvFindXFromFile =
      _GcvFindXFromFilePtr.asFunction<
        void Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>, int)
      >();

  void BitmapOpenFind(ffi.Pointer<ffi.Char> path, int port) {
    return _BitmapOpenFind(path, port);
  }

  late final _BitmapOpenFindPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<ffi.Char>, ffi.LongLong)
        >
      >('BitmapOpenFind');
  late final _BitmapOpenFind =
      _BitmapOpenFindPtr.asFunction<
        void Function(ffi.Pointer<ffi.Char>, int)
      >();

  void BitmapFindAllFromFile(ffi.Pointer<ffi.Char> path, int port) {
    return _BitmapFindAllFromFile(path, port);
  }

  late final _BitmapFindAllFromFilePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<ffi.Char>, ffi.LongLong)
        >
      >('BitmapFindAllFromFile');
  late final _BitmapFindAllFromFile =
      _BitmapFindAllFromFilePtr.asFunction<
        void Function(ffi.Pointer<ffi.Char>, int)
      >();

  void MoveToFoundFromFile(ffi.Pointer<ffi.Char> path, int port) {
    return _MoveToFoundFromFile(path, port);
  }

  late final _MoveToFoundFromFilePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<ffi.Char>, ffi.LongLong)
        >
      >('MoveToFoundFromFile');
  late final _MoveToFoundFromFile =
      _MoveToFoundFromFilePtr.asFunction<
        void Function(ffi.Pointer<ffi.Char>, int)
      >();

  void HookRegisterCombo(
    ffi.Pointer<ffi.Char> mods,
    ffi.Pointer<ffi.Char> key,
    int port,
  ) {
    return _HookRegisterCombo(mods, key, port);
  }

  late final _HookRegisterComboPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Char>,
            ffi.LongLong,
          )
        >
      >('HookRegisterCombo');
  late final _HookRegisterCombo =
      _HookRegisterComboPtr.asFunction<
        void Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>, int)
      >();

  void HookStart(int port) {
    return _HookStart(port);
  }

  late final _HookStartPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.LongLong)>>('HookStart');
  late final _HookStart = _HookStartPtr.asFunction<void Function(int)>();

  void HookStop() {
    return _HookStop();
  }

  late final _HookStopPtr = _lookup<ffi.NativeFunction<ffi.Void Function()>>(
    'HookStop',
  );
  late final _HookStop = _HookStopPtr.asFunction<void Function()>();

  void HookAddEvent(ffi.Pointer<ffi.Char> name, int port) {
    return _HookAddEvent(name, port);
  }

  late final _HookAddEventPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<ffi.Char>, ffi.LongLong)
        >
      >('HookAddEvent');
  late final _HookAddEvent =
      _HookAddEventPtr.asFunction<void Function(ffi.Pointer<ffi.Char>, int)>();

  void DecodeAndReportImageSize(ffi.Pointer<ffi.Char> path, int port) {
    return _DecodeAndReportImageSize(path, port);
  }

  late final _DecodeAndReportImageSizePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<ffi.Char>, ffi.LongLong)
        >
      >('DecodeAndReportImageSize');
  late final _DecodeAndReportImageSize =
      _DecodeAndReportImageSizePtr.asFunction<
        void Function(ffi.Pointer<ffi.Char>, int)
      >();
}

typedef ptrdiff_t = ffi.Long;
typedef Dartptrdiff_t = int;

final class max_align_t extends ffi.Opaque {}

final class _GoString_ extends ffi.Struct {
  external ffi.Pointer<ffi.Char> p;

  @ptrdiff_t()
  external int n;
}

typedef __u_char = ffi.UnsignedChar;
typedef Dart__u_char = int;
typedef __u_short = ffi.UnsignedShort;
typedef Dart__u_short = int;
typedef __u_int = ffi.UnsignedInt;
typedef Dart__u_int = int;
typedef __u_long = ffi.UnsignedLong;
typedef Dart__u_long = int;
typedef __int8_t = ffi.SignedChar;
typedef Dart__int8_t = int;
typedef __uint8_t = ffi.UnsignedChar;
typedef Dart__uint8_t = int;
typedef __int16_t = ffi.Short;
typedef Dart__int16_t = int;
typedef __uint16_t = ffi.UnsignedShort;
typedef Dart__uint16_t = int;
typedef __int32_t = ffi.Int;
typedef Dart__int32_t = int;
typedef __uint32_t = ffi.UnsignedInt;
typedef Dart__uint32_t = int;
typedef __int64_t = ffi.Long;
typedef Dart__int64_t = int;
typedef __uint64_t = ffi.UnsignedLong;
typedef Dart__uint64_t = int;
typedef __int_least8_t = __int8_t;
typedef __uint_least8_t = __uint8_t;
typedef __int_least16_t = __int16_t;
typedef __uint_least16_t = __uint16_t;
typedef __int_least32_t = __int32_t;
typedef __uint_least32_t = __uint32_t;
typedef __int_least64_t = __int64_t;
typedef __uint_least64_t = __uint64_t;
typedef __quad_t = ffi.Long;
typedef Dart__quad_t = int;
typedef __u_quad_t = ffi.UnsignedLong;
typedef Dart__u_quad_t = int;
typedef __intmax_t = ffi.Long;
typedef Dart__intmax_t = int;
typedef __uintmax_t = ffi.UnsignedLong;
typedef Dart__uintmax_t = int;
typedef __dev_t = ffi.UnsignedLong;
typedef Dart__dev_t = int;
typedef __uid_t = ffi.UnsignedInt;
typedef Dart__uid_t = int;
typedef __gid_t = ffi.UnsignedInt;
typedef Dart__gid_t = int;
typedef __ino_t = ffi.UnsignedLong;
typedef Dart__ino_t = int;
typedef __ino64_t = ffi.UnsignedLong;
typedef Dart__ino64_t = int;
typedef __mode_t = ffi.UnsignedInt;
typedef Dart__mode_t = int;
typedef __nlink_t = ffi.UnsignedLong;
typedef Dart__nlink_t = int;
typedef __off_t = ffi.Long;
typedef Dart__off_t = int;
typedef __off64_t = ffi.Long;
typedef Dart__off64_t = int;
typedef __pid_t = ffi.Int;
typedef Dart__pid_t = int;

final class __fsid_t extends ffi.Struct {
  @ffi.Array.multi([2])
  external ffi.Array<ffi.Int> __val;
}

typedef __clock_t = ffi.Long;
typedef Dart__clock_t = int;
typedef __rlim_t = ffi.UnsignedLong;
typedef Dart__rlim_t = int;
typedef __rlim64_t = ffi.UnsignedLong;
typedef Dart__rlim64_t = int;
typedef __id_t = ffi.UnsignedInt;
typedef Dart__id_t = int;
typedef __time_t = ffi.Long;
typedef Dart__time_t = int;
typedef __useconds_t = ffi.UnsignedInt;
typedef Dart__useconds_t = int;
typedef __suseconds_t = ffi.Long;
typedef Dart__suseconds_t = int;
typedef __suseconds64_t = ffi.Long;
typedef Dart__suseconds64_t = int;
typedef __daddr_t = ffi.Int;
typedef Dart__daddr_t = int;
typedef __key_t = ffi.Int;
typedef Dart__key_t = int;
typedef __clockid_t = ffi.Int;
typedef Dart__clockid_t = int;
typedef __timer_t = ffi.Pointer<ffi.Void>;
typedef __blksize_t = ffi.Long;
typedef Dart__blksize_t = int;
typedef __blkcnt_t = ffi.Long;
typedef Dart__blkcnt_t = int;
typedef __blkcnt64_t = ffi.Long;
typedef Dart__blkcnt64_t = int;
typedef __fsblkcnt_t = ffi.UnsignedLong;
typedef Dart__fsblkcnt_t = int;
typedef __fsblkcnt64_t = ffi.UnsignedLong;
typedef Dart__fsblkcnt64_t = int;
typedef __fsfilcnt_t = ffi.UnsignedLong;
typedef Dart__fsfilcnt_t = int;
typedef __fsfilcnt64_t = ffi.UnsignedLong;
typedef Dart__fsfilcnt64_t = int;
typedef __fsword_t = ffi.Long;
typedef Dart__fsword_t = int;
typedef __ssize_t = ffi.Long;
typedef Dart__ssize_t = int;
typedef __syscall_slong_t = ffi.Long;
typedef Dart__syscall_slong_t = int;
typedef __syscall_ulong_t = ffi.UnsignedLong;
typedef Dart__syscall_ulong_t = int;
typedef __loff_t = __off64_t;
typedef __caddr_t = ffi.Pointer<ffi.Char>;
typedef __intptr_t = ffi.Long;
typedef Dart__intptr_t = int;
typedef __socklen_t = ffi.UnsignedInt;
typedef Dart__socklen_t = int;
typedef __sig_atomic_t = ffi.Int;
typedef Dart__sig_atomic_t = int;
typedef int_least8_t = __int_least8_t;
typedef int_least16_t = __int_least16_t;
typedef int_least32_t = __int_least32_t;
typedef int_least64_t = __int_least64_t;
typedef uint_least8_t = __uint_least8_t;
typedef uint_least16_t = __uint_least16_t;
typedef uint_least32_t = __uint_least32_t;
typedef uint_least64_t = __uint_least64_t;
typedef int_fast8_t = ffi.SignedChar;
typedef Dartint_fast8_t = int;
typedef int_fast16_t = ffi.Long;
typedef Dartint_fast16_t = int;
typedef int_fast32_t = ffi.Long;
typedef Dartint_fast32_t = int;
typedef int_fast64_t = ffi.Long;
typedef Dartint_fast64_t = int;
typedef uint_fast8_t = ffi.UnsignedChar;
typedef Dartuint_fast8_t = int;
typedef uint_fast16_t = ffi.UnsignedLong;
typedef Dartuint_fast16_t = int;
typedef uint_fast32_t = ffi.UnsignedLong;
typedef Dartuint_fast32_t = int;
typedef uint_fast64_t = ffi.UnsignedLong;
typedef Dartuint_fast64_t = int;
typedef intmax_t = __intmax_t;
typedef uintmax_t = __uintmax_t;
typedef GoInt8 = ffi.SignedChar;
typedef DartGoInt8 = int;
typedef GoUint8 = ffi.UnsignedChar;
typedef DartGoUint8 = int;
typedef GoInt16 = ffi.Short;
typedef DartGoInt16 = int;
typedef GoUint16 = ffi.UnsignedShort;
typedef DartGoUint16 = int;
typedef GoInt32 = ffi.Int;
typedef DartGoInt32 = int;
typedef GoUint32 = ffi.UnsignedInt;
typedef DartGoUint32 = int;
typedef GoInt64 = ffi.LongLong;
typedef DartGoInt64 = int;
typedef GoUint64 = ffi.UnsignedLongLong;
typedef DartGoUint64 = int;
typedef GoInt = GoInt64;
typedef GoUint = GoUint64;
typedef GoUintptr = ffi.Size;
typedef DartGoUintptr = int;
typedef GoFloat32 = ffi.Float;
typedef DartGoFloat32 = double;
typedef GoFloat64 = ffi.Double;
typedef DartGoFloat64 = double;
typedef GoString = _GoString_;
typedef GoMap = ffi.Pointer<ffi.Void>;
typedef GoChan = ffi.Pointer<ffi.Void>;

final class GoInterface extends ffi.Struct {
  external ffi.Pointer<ffi.Void> t;

  external ffi.Pointer<ffi.Void> v;
}

final class GoSlice extends ffi.Struct {
  external ffi.Pointer<ffi.Void> data;

  @GoInt()
  external int len;

  @GoInt()
  external int cap;
}

const int NULL = 0;

const int _STDINT_H = 1;

const int _FEATURES_H = 1;

const int _DEFAULT_SOURCE = 1;

const int __GLIBC_USE_ISOC2X = 1;

const int __USE_ISOC11 = 1;

const int __USE_ISOC99 = 1;

const int __USE_ISOC95 = 1;

const int _POSIX_SOURCE = 1;

const int _POSIX_C_SOURCE = 200809;

const int __USE_POSIX = 1;

const int __USE_POSIX2 = 1;

const int __USE_POSIX199309 = 1;

const int __USE_POSIX199506 = 1;

const int __USE_XOPEN2K = 1;

const int __USE_XOPEN2K8 = 1;

const int _ATFILE_SOURCE = 1;

const int __WORDSIZE = 64;

const int __WORDSIZE_TIME64_COMPAT32 = 1;

const int __SYSCALL_WORDSIZE = 64;

const int __TIMESIZE = 64;

const int __USE_MISC = 1;

const int __USE_ATFILE = 1;

const int __USE_FORTIFY_LEVEL = 0;

const int __GLIBC_USE_DEPRECATED_GETS = 0;

const int __GLIBC_USE_DEPRECATED_SCANF = 0;

const int _STDC_PREDEF_H = 1;

const int __STDC_IEC_559__ = 1;

const int __STDC_IEC_60559_BFP__ = 201404;

const int __STDC_IEC_559_COMPLEX__ = 1;

const int __STDC_IEC_60559_COMPLEX__ = 201404;

const int __STDC_ISO_10646__ = 201706;

const int __GNU_LIBRARY__ = 6;

const int __GLIBC__ = 2;

const int __GLIBC_MINOR__ = 36;

const int _SYS_CDEFS_H = 1;

const int __THROW = 1;

const int __THROWNL = 1;

const int __glibc_c99_flexarr_available = 1;

const int __LDOUBLE_REDIRECTS_TO_FLOAT128_ABI = 0;

const int __HAVE_GENERIC_SELECTION = 0;

const int __GLIBC_USE_LIB_EXT2 = 1;

const int __GLIBC_USE_IEC_60559_BFP_EXT = 1;

const int __GLIBC_USE_IEC_60559_BFP_EXT_C2X = 1;

const int __GLIBC_USE_IEC_60559_EXT = 1;

const int __GLIBC_USE_IEC_60559_FUNCS_EXT = 1;

const int __GLIBC_USE_IEC_60559_FUNCS_EXT_C2X = 1;

const int __GLIBC_USE_IEC_60559_TYPES_EXT = 1;

const int _BITS_TYPES_H = 1;

const int _BITS_TYPESIZES_H = 1;

const int __OFF_T_MATCHES_OFF64_T = 1;

const int __INO_T_MATCHES_INO64_T = 1;

const int __RLIM_T_MATCHES_RLIM64_T = 1;

const int __STATFS_MATCHES_STATFS64 = 1;

const int __KERNEL_OLD_TIMEVAL_MATCHES_TIMEVAL64 = 1;

const int __FD_SETSIZE = 1024;

const int _BITS_TIME64_H = 1;

const int _BITS_WCHAR_H = 1;

const int __WCHAR_MAX = 2147483647;

const int __WCHAR_MIN = -2147483648;

const int _BITS_STDINT_INTN_H = 1;

const int _BITS_STDINT_UINTN_H = 1;

const int INT8_MIN = -128;

const int INT16_MIN = -32768;

const int INT32_MIN = -2147483648;

const int INT64_MIN = -9223372036854775808;

const int INT8_MAX = 127;

const int INT16_MAX = 32767;

const int INT32_MAX = 2147483647;

const int INT64_MAX = 9223372036854775807;

const int UINT8_MAX = 255;

const int UINT16_MAX = 65535;

const int UINT32_MAX = 4294967295;

const int UINT64_MAX = -1;

const int INT_LEAST8_MIN = -128;

const int INT_LEAST16_MIN = -32768;

const int INT_LEAST32_MIN = -2147483648;

const int INT_LEAST64_MIN = -9223372036854775808;

const int INT_LEAST8_MAX = 127;

const int INT_LEAST16_MAX = 32767;

const int INT_LEAST32_MAX = 2147483647;

const int INT_LEAST64_MAX = 9223372036854775807;

const int UINT_LEAST8_MAX = 255;

const int UINT_LEAST16_MAX = 65535;

const int UINT_LEAST32_MAX = 4294967295;

const int UINT_LEAST64_MAX = -1;

const int INT_FAST8_MIN = -128;

const int INT_FAST16_MIN = -9223372036854775808;

const int INT_FAST32_MIN = -9223372036854775808;

const int INT_FAST64_MIN = -9223372036854775808;

const int INT_FAST8_MAX = 127;

const int INT_FAST16_MAX = 9223372036854775807;

const int INT_FAST32_MAX = 9223372036854775807;

const int INT_FAST64_MAX = 9223372036854775807;

const int UINT_FAST8_MAX = 255;

const int UINT_FAST16_MAX = -1;

const int UINT_FAST32_MAX = -1;

const int UINT_FAST64_MAX = -1;

const int INTPTR_MIN = -9223372036854775808;

const int INTPTR_MAX = 9223372036854775807;

const int UINTPTR_MAX = -1;

const int INTMAX_MIN = -9223372036854775808;

const int INTMAX_MAX = 9223372036854775807;

const int UINTMAX_MAX = -1;

const int PTRDIFF_MIN = -9223372036854775808;

const int PTRDIFF_MAX = 9223372036854775807;

const int SIG_ATOMIC_MIN = -2147483648;

const int SIG_ATOMIC_MAX = 2147483647;

const int SIZE_MAX = -1;

const int WCHAR_MIN = -2147483648;

const int WCHAR_MAX = 2147483647;

const int WINT_MIN = 0;

const int WINT_MAX = 4294967295;
