/* Code generated by cmd/cgo; DO NOT EDIT. */

/* package screengot */


#line 1 "cgo-builtin-export-prolog"

#include <stddef.h>

#ifndef GO_CGO_EXPORT_PROLOGUE_H
#define GO_CGO_EXPORT_PROLOGUE_H

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef struct { const char *p; ptrdiff_t n; } _GoString_;
extern size_t _GoStringLen(_GoString_ s);
extern const char *_GoStringPtr(_GoString_ s);
#endif

#endif

/* Start of preamble from import "C" comments.  */


#line 3 "main.go"

#include <stdint.h>

#line 1 "cgo-generated-wrapper"


/* End of preamble from import "C" comments.  */


/* Start of boilerplate cgo prologue.  */
#line 1 "cgo-gcc-export-header-prolog"

#ifndef GO_CGO_PROLOGUE_H
#define GO_CGO_PROLOGUE_H

typedef signed char GoInt8;
typedef unsigned char GoUint8;
typedef short GoInt16;
typedef unsigned short GoUint16;
typedef int GoInt32;
typedef unsigned int GoUint32;
typedef long long GoInt64;
typedef unsigned long long GoUint64;
typedef GoInt64 GoInt;
typedef GoUint64 GoUint;
typedef size_t GoUintptr;
typedef float GoFloat32;
typedef double GoFloat64;
#ifdef _MSC_VER
#if !defined(__cplusplus) || _MSVC_LANG <= 201402L
#include <complex.h>
typedef _Fcomplex GoComplex64;
typedef _Dcomplex GoComplex128;
#else
#include <complex>
typedef std::complex<float> GoComplex64;
typedef std::complex<double> GoComplex128;
#endif
#else
typedef float _Complex GoComplex64;
typedef double _Complex GoComplex128;
#endif

/*
  static assertion to make sure the file is being used on architecture
  at least with matching size of GoInt.
*/
typedef char _check_for_64_bit_pointer_matching_GoInt[sizeof(void*)==64/8 ? 1:-1];

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef _GoString_ GoString;
#endif
typedef void *GoMap;
typedef void *GoChan;
typedef struct { void *t; void *v; } GoInterface;
typedef struct { void *data; GoInt len; GoInt cap; } GoSlice;

#endif

/* End of boilerplate cgo prologue.  */

#ifdef __cplusplus
extern "C" {
#endif

extern void RegisterPort(long long int port);
extern void UnregisterPort(void);
extern void StopTask(long long int taskID, long long int port);

// ---- Bridge init to call bridge.InitDartApi(...) from Dart ----
extern void BridgeInit(void* api);

// ---- synchronous operations ----
extern void Move(int x, int y, long long int port);
extern void MoveRelative(int x, int y, long long int port);
extern void Click(char* btn, int dbl, long long int port);
extern void Toggle(char* btn, char* dir, long long int port);
extern void Scroll(int x, int y, long long int port);
extern void ScrollDir(int amount, char* dir, long long int port);
extern void GetLocation(long long int port);
extern void SetMouseSleep(int ms, long long int port);
extern void MilliSleep(int ms, long long int port);
extern long long int MoveSmoothStart(int x, int y, long long int port);
extern long long int DragSmoothStart(int x, int y, long long int port);
extern long long int ScrollSmoothStart(int x, int y, long long int port);
extern void TypeStr(char* text, long long int port);

// allows calling robotgo.TypeStr(s, int1, int2) (some usages pass additional ints)
extern void TypeStrWithInts(char* text, int arg1, int arg2, long long int port);
extern void Sleep(int seconds, long long int port);
extern void SetKeySleep(int ms, long long int port);

// mods: comma separated modifiers string like "alt,cmd" or NULL for none
extern void KeyTap(char* key, char* mods, long long int port);

// modsJson: JSON array string like '["alt","cmd"]'
extern void KeyTapArr(char* key, char* modsJson, long long int port);

// direction: NULL for default, or "up" / "down"
extern void KeyToggle(char* key, char* direction, long long int port);
extern void WriteAll(char* text, long long int port);
extern void ReadAll(long long int port);
extern long long int TypeStrStart(char* text, long long int port);
extern void GetPixelColor(int x, int y, long long int port);
extern void GetScreenSize(long long int port);
extern void CaptureScreenSave(int x, int y, int w, int h, char* path, long long int port);

// returns a base64-encoded PNG of the captured region in the "data" response field.
extern void CaptureScreenBase64(int x, int y, int w, int h, long long int port);
extern void DisplaysNum(long long int port);
extern void GetDisplayBounds(int index, long long int port);

// capture entire display specified by index and save to given path (if path NULL, create temp file)
extern void CaptureDisplaySave(int index, char* path, long long int port);

// capture specific region on current display (or after setting DisplayID) and save
extern void CaptureDisplayRegionSave(int index, int x, int y, int w, int h, char* path, long long int port);

// save an image.Image (captured via CaptureImg) to jpeg with quality (0-100).
// Here we accept path and quality; we capture entire display at robotgo.DisplayID.
extern void SaveImageJpeg(char* path, int quality, long long int port);

// capture current display and save PNG to path
extern void SaveImagePNGFromCaptureImg(char* path, long long int port);

// capture a region and save the raw bitmap to a file using bitmap.Save.
// If path is NULL or empty a temp filename is created (returned).
extern void CaptureScreenBitmapSave(int x, int y, int w, int h, char* path, long long int port);

// capture region -> convert -> search on screen -> return found coords {x,y}
// This uses the same approach as your example: capture -> ToImage -> ImgToBitmap -> ToCBitmap -> bitmap.Find
extern void FindBitmapFromCapture(int x, int y, int w, int h, long long int port);

// capture region -> convert -> find all occurrences on screen -> return array of points
extern void FindAllBitmapFromCapture(int x, int y, int w, int h, long long int port);

// After finding coordinates (fx,fy) this convenience function moves the mouse to them.
extern void MoveToFoundBitmap(int x, int y, int w, int h, long long int port);

// Save a captured region to a file (PNG). This uses robotgo.ToImage + robotgo.Save (or bitmap.Save).
extern void SaveBitmapToFile(int x, int y, int w, int h, char* path, long long int port);
extern void SaveCaptureRegion(char* path, int x, int y, int w, int h, long long int port);
extern void SaveCaptureFull(char* path, long long int port);
extern void GcvFindAllImgFile(char* templatePath, char* targetPath, long long int port);
extern void GcvFindAllImgFilesDecoded(char* templatePath, char* targetPath, long long int port);
extern void GcvFindXFromFile(char* templatePath, char* targetPath, long long int port);
extern void BitmapOpenFind(char* path, long long int port);
extern void BitmapFindAllFromFile(char* path, long long int port);
extern void MoveToFoundFromFile(char* path, long long int port);
extern void HookRegisterCombo(char* mods, char* key, long long int port);
extern void HookStart(long long int port);
extern void HookStop(void);
extern void HookAddEvent(char* name, long long int port);

// convenience debug helper: decode image file and return width/height
extern void DecodeAndReportImageSize(char* path, long long int port);

#ifdef __cplusplus
}
#endif
