/* Code generated by cmd/cgo; DO NOT EDIT. */

/* package tgo */


#line 1 "cgo-builtin-export-prolog"

#include <stddef.h>

#ifndef GO_CGO_EXPORT_PROLOGUE_H
#define GO_CGO_EXPORT_PROLOGUE_H

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef struct { const char *p; ptrdiff_t n; } _GoString_;
extern size_t _GoStringLen(_GoString_ s);
extern const char *_GoStringPtr(_GoString_ s);
#endif

#endif

/* Start of preamble from import "C" comments.  */


#line 3 "main.go"

#include <stdlib.h>
#include <string.h>

// Define the functions accessible from Dart/C
extern int StartShell(void);
extern char* ReadOutput(int session_id);
extern void WriteInput(int session_id, char* input);
extern void CloseShell(int session_id);
extern int Bs4Find(int session_id, char* election);
extern char* Bs4Finds(int session_id, char* election);
extern char* Bs4Text(int session_id);
extern char* Bs4Attrs(int session_id);
extern void CloseBs4Client(int session_id);

// PDF Generation
extern char* GenerateSimplePdf(char* outputPath, char* fontPath, char* text);

// PDF Generation State Management
extern int StartPdfSession(void);
extern void ClosePdfSession(int session_id);
extern char* PdfAddPage(int session_id);
extern char* PdfAddFont(int session_id, char* key, char* path);
extern char* PdfSetFont(int session_id, char* family, char* style, int size);
extern char* PdfWritePdf(int session_id, char* path);
extern int StartSSH(char* user, char* host, char* password, char* keyPath, char* passphrase, int useAgent);
extern char* RunRemoteCommand(int session_id, char* command, int timeoutSeconds);
extern int RemoteFileTransfer(int session_id, int transferType, char* localPath, char* remotePath);
extern void CloseSSH(int session_id);
// PDF Text and Style
extern char* PdfSetTextColorRGB(int session_id, int r, int g, int b);
extern char* PdfText(int session_id, char* content);
extern char* PdfSetXY(int session_id, float x, float y);

// PDF Images and Rotation
extern char* PdfAddImage(int session_id, char* path, float x, float y);
extern char* PdfRotate(int session_id, float angle, float x, float y);
extern char* PdfRotateReset(int session_id);

// Text Diffing
extern char* TextDiff(char* text1, char* text2);

// ... rest of the file
// HTTP Server Functions
extern int StartStaticFileServer(char* port, char* baseDir);
extern char* StopStaticFileServer(int server_id);

// Git Functions (Worktree operations)
extern char* GitAdd(char* directory, char* filePath);
extern char* GitCommit(char* directory, char* message, char* authorName, char* authorEmail);

// HTTP Client Functions
extern int NewHttpClient(void);
extern void CloseHttpClient(int session_id);
extern void HttpClientCloseIdleConnections(int session_id);
extern char* HttpGet(int session_id, char* requestUrl);
extern char* HttpPostForm(int session_id, char* requestUrl, char* formJson);

// BS4 Management and Creation
extern int NewBs4Client(char* txt, char* baseUrl);
extern int Bs4Copy(int session_id);

// BS4 Retrieval (Returning IDs)
extern int Bs4Find(int session_id, char* election);
extern int Bs4Next(int session_id, char* electionsJson);
extern char* Bs4Childrens(int session_id, char* electionsJson);
extern char* Bs4Parents(int session_id, char* electionsJson);
extern char* Bs4Finds(int session_id, char* election); // Already defined in previous step

// BS4 Getters (Returning Data)
extern char* Bs4Text(int session_id); // Already defined in previous step
extern char* Bs4Attrs(int session_id); // Already defined in previous step
extern char* Bs4Get(int session_id, char* key, char* defaultVal);
extern char* Bs4Html(int session_id, char* content);
extern char* Bs4Strings(int session_id);

// BS4 Setters/Manipulation
extern void Bs4Set(int session_id, char* key, char* val);
extern void Bs4Append(int session_id, char* str);
extern void Bs4Remove(int session_id);
extern void Bs4Clear(int session_id);

// Data Analysis (DataFrame/Series)
// NOTE: We assume a DataSession ID exists.
extern char* DescribeData(int session_id, char* optsJson);
extern char* DataDropNil(int session_id);
extern char* DataFillNil(int session_id, char* replaceValJson);

// PDF Links
extern char* PdfAddExternalLink(int session_id, char* url, float x, float y, float w, float h);

// PDF Drawing
extern char* PdfSetLineWidth(int session_id, float width);
extern char* PdfLine(int session_id, float x1, float y1, float x2, float y2);
extern char* PdfRectangle(int session_id, float x, float y, float w, float h, char* style, float r, int dot);
// Git Functions
extern char* GitClone(char* repoUrl, char* directory);
extern char* GitPull(char* directory);
extern char* GitPush(char* directory); // <-- NEW

// Git Functions (Advanced)
extern char* GitRemoteAdd(char* directory, char* remoteName, char* remoteUrl);
extern char* GitRemoteDelete(char* directory, char* remoteName);
extern char* GitRemoteList(char* directory);
extern char* GitFetch(char* directory, char* remoteName);

#line 1 "cgo-generated-wrapper"


/* End of preamble from import "C" comments.  */


/* Start of boilerplate cgo prologue.  */
#line 1 "cgo-gcc-export-header-prolog"

#ifndef GO_CGO_PROLOGUE_H
#define GO_CGO_PROLOGUE_H

typedef signed char GoInt8;
typedef unsigned char GoUint8;
typedef short GoInt16;
typedef unsigned short GoUint16;
typedef int GoInt32;
typedef unsigned int GoUint32;
typedef long long GoInt64;
typedef unsigned long long GoUint64;
typedef GoInt64 GoInt;
typedef GoUint64 GoUint;
typedef size_t GoUintptr;
typedef float GoFloat32;
typedef double GoFloat64;
#ifdef _MSC_VER
#if !defined(__cplusplus) || _MSVC_LANG <= 201402L
#include <complex.h>
typedef _Fcomplex GoComplex64;
typedef _Dcomplex GoComplex128;
#else
#include <complex>
typedef std::complex<float> GoComplex64;
typedef std::complex<double> GoComplex128;
#endif
#else
typedef float _Complex GoComplex64;
typedef double _Complex GoComplex128;
#endif

/*
  static assertion to make sure the file is being used on architecture
  at least with matching size of GoInt.
*/
typedef char _check_for_64_bit_pointer_matching_GoInt[sizeof(void*)==64/8 ? 1:-1];

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef _GoString_ GoString;
#endif
typedef void *GoMap;
typedef void *GoChan;
typedef struct { void *t; void *v; } GoInterface;
typedef struct { void *data; GoInt len; GoInt cap; } GoSlice;

#endif

/* End of boilerplate cgo prologue.  */

#ifdef __cplusplus
extern "C" {
#endif


// ClosePdfSession removes the session (crucial after calling WritePdf).
extern void ClosePdfSession(int session_id);
extern int NewHttpClient(void);

// CloseHttpClient closes the client and removes it from the map.
// Note: This does NOT close active requests, only frees the client object.
extern void CloseHttpClient(int session_id);

// HttpGet issues a GET request and returns a JSON string containing HttpResponseData.
extern char* HttpGet(int session_id, char* requestUrl);
extern char* HttpPostForm(int session_id, char* requestUrl, char* formJson);

// GitPull pulls the latest changes from the 'origin' remote into the current branch.
// Returns a string containing the result status (success or detailed error).
extern char* GitPull(char* directory);

// GitPush pushes local changes to the configured remote (usually 'origin').
// Returns a string containing the result status (success or detailed error).
extern char* GitPush(char* directory);

// GitAdd adds a specific file or directory (path) to the staging area.
// Returns a string containing the result status.
extern char* GitAdd(char* directory, char* filePath);

// GitRemoteAdd adds a new remote to the repository.
// Returns a string containing the result status.
extern char* GitRemoteAdd(char* directory, char* remoteName, char* remoteUrl);

// GitRemoteDelete removes a remote from the repository.
// Returns a string containing the result status.
extern char* GitRemoteDelete(char* directory, char* remoteName);

// GitRemoteList lists all configured remotes.
// Returns a JSON string array of remote information.
extern char* GitRemoteList(char* directory);

// C.StartSSH establishes an SSH connection.
// Returns a unique session ID (integer) or 0 on failure.
extern int StartSSH(char* user, char* host, char* password, char* keyPath, char* passphrase, int useAgent);

// C.RunRemoteCommand executes a command on the remote host.
// Returns the output as a C string (caller must free).
extern char* RunRemoteCommand(int session_id, char* command, int timeoutSeconds);

// C.RemoteFileTransfer performs file uploads and downloads.
// 0 for Upload (local to remote), 1 for Download (remote to local).
// Returns 0 on success, 1 on failure.
extern int RemoteFileTransfer(int session_id, int transferType, char* localPath, char* remotePath);

// C.CloseSSH cleans up the SSH client and SFTP connection.
extern void CloseSSH(int session_id);

// C.StartShell starts a shell process (bash/powershell) and allocates a PTY.
// Returns a unique session ID (integer).
extern int StartShell(void);

// C.ReadOutput blocks until output is available from the shell, then returns it as a C string.
// Caller is responsible for freeing the memory (via C.free in Dart).
extern char* ReadOutput(int session_id);

// C.WriteInput sends data from the Flutter UI to the shell's stdin.
extern void WriteInput(int session_id, char* input);

// C.CloseShell cleans up the resources and kills the shell process.
extern void CloseShell(int session_id);
extern int NewBs4Client(char* txt, char* baseUrl);
extern int Bs4Copy(int session_id);

// Find single element (returns new ID)
extern int Bs4Find(int session_id, char* election);

// Find multiple elements (returns JSON array of IDs)
extern char* Bs4Childrens(int session_id, char* electionsJson);

// Find multiple elements (returns JSON array of IDs)
extern char* Bs4Parents(int session_id, char* electionsJson);

// Find single next sibling (returns new ID)
extern int Bs4Next(int session_id, char* electionsJson);
extern char* Bs4Get(int session_id, char* key, char* defaultVal);
extern char* Bs4Html(int session_id, char* content);
extern char* Bs4Strings(int session_id);
extern void Bs4Set(int session_id, char* key, char* val);
extern void Bs4Append(int session_id, char* str);
extern void Bs4Remove(int session_id);
extern void Bs4Clear(int session_id);

#ifdef __cplusplus
}
#endif
