display_name: GPT Box
package_name: cn.lpkt.gptbox
maintainer:
  name: lollipopkit
  email: 10864310+lollipopkit@users.noreply.github.com
# co_authors:
#   - name: 
#     email: 
priority: optional
section: x11
installed_size: 6604
essential: false
icon: assets/app_icon.png

# postinstall_scripts:
#   - echo "Installed my awesome app"
# postuninstall_scripts:
#   - echo "Surprised Pickachu face"

keywords:
  - gpt
  - chat
  - openai
  - ai

generic_name: GPT Box

categories:
  - Utility

startup_notify: true