// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';

import 'package:gpt_box/hive/hive_adapters.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(ChatConfigAdapter());
    registerAdapter(ChatContentAdapter());
    registerAdapter(ChatContentTypeAdapter());
    registerAdapter(ChatFolderAdapter());
    registerAdapter(ChatHistoryAdapter());
    registerAdapter(ChatHistoryItemAdapter());
    registerAdapter(ChatRoleAdapter());
    registerAdapter(ChatSettingsAdapter());
    registerAdapter(ChatTypeAdapter());
    registerAdapter(DownloadItemAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(ChatConfigAdapter());
    registerAdapter(ChatContentAdapter());
    registerAdapter(ChatContentTypeAdapter());
    registerAdapter(ChatFolderAdapter());
    registerAdapter(ChatHistoryAdapter());
    registerAdapter(ChatHistoryItemAdapter());
    registerAdapter(ChatRoleAdapter());
    registerAdapter(ChatSettingsAdapter());
    registerAdapter(ChatTypeAdapter());
    registerAdapter(DownloadItemAdapter());
  }
}
