// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:gpt_box/hive/hive_adapters.dart';
import 'package:gpt_box/view/translator/configuration/translator_config.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(ChatConfigAdapter());
    registerAdapter(ChatContentAdapter());
    registerAdapter(ChatContentTypeAdapter());
    registerAdapter(ChatHistoryAdapter());
    registerAdapter(ChatHistoryItemAdapter());
    registerAdapter(ChatRoleAdapter());
    registerAdapter(ChatSettingsAdapter());
    registerAdapter(ChatTypeAdapter());
    registerAdapter(DownloadItemAdapter());
    registerAdapter(TranslatorConfigAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(ChatConfigAdapter());
    registerAdapter(ChatContentAdapter());
    registerAdapter(ChatContentTypeAdapter());
    registerAdapter(ChatHistoryAdapter());
    registerAdapter(ChatHistoryItemAdapter());
    registerAdapter(ChatRoleAdapter());
    registerAdapter(ChatSettingsAdapter());
    registerAdapter(ChatTypeAdapter());
    registerAdapter(DownloadItemAdapter());
    registerAdapter(TranslatorConfigAdapter());
  }
}
